import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "module";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const workerBuild = await esbuild.build({
	entryPoints: ["src/embedding/host/worker/bootstrap.ts"],
	bundle: true,
	platform: "browser",
	format: "iife",
	target: "esnext",
	write: false,
	minify: prod,
});
// Obsidian's BrowserWindow sets `nodeIntegrationInWorker: true` (with `contextIsolation: false`),
// so a Worker created here still gets a real Node `process` global, injected as a plain mutable
// property (not a locked-down proxy). @huggingface/transformers treats `process.release.name === 'node'`
// as proof it's running server-side and restricts itself to the `cpu` execution provider, hiding
// WebGPU/WASM device support in the process. Stripping `process` from *this worker's own* global
// scope only (nothing else runs in it) before any bundled module evaluates makes the library correctly
// detect a browser-like environment instead. This must run before the bundle's own module graph
// evaluates (import hoisting would otherwise run transformers.js's env detection first), so it's
// prepended as raw text ahead of the bundle rather than written as part of bootstrap.ts.
const workerEnvironmentShim = `try { delete self.process; } catch (e) { try { self.process = undefined; } catch (e2) {} }\n`;
const workerCodeString = JSON.stringify(workerEnvironmentShim + workerBuild.outputFiles[0].text);

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	platform: 'node',
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	define: {
		__WORKER_CONTENTS_PLACEHOLDER__: workerCodeString, // Inline the bundled embedding worker code
		__DEV__: JSON.stringify(!prod), // Dev-only features; folds to `false` in production so they're tree-shaken out
	},
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
